image: $DOCKER_REGISTRY_PREFIX/2smart/utils/combined-ci-image:latest

stages:
  - test
  - build
  - push
  - update

services:
  - name: registry.gitlab.webbylab.com/smarthome/base-images/docker-dind
    alias: docker

build:
  stage: build
  script:
    - git clone https://oauth2:$ACCESS_TOKEN@gitlab.webbylab.com/SmartHome/docker-utils.git
    - mv docker-utils/utils.sh docker.sh
    - ./docker.sh rundaemon
    - ./docker.sh build
    - ./docker.sh push
  only:
    - 'master'
